[package]
name = "edu-base64"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = "0.11"
phf = { version = "0.11", default-features = false, features = ["macros"] }

[dev-dependencies]
proptest = "1.4.0"
